# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfc8b9751ed027ef9f27d7c4fcd682422421f10d9a33d28daca4326f2fba89ce4ab44c6ac6e83c05aec337205e4b3f9299074b6fbecb17d5fa1892cb40c8dfb1

test:
  secret_key_base: c4b90e9160bb8c6bceb0e072f32dfdae78bc31bd0f003361a6be5da6b59624c593ab3262084587fa9cafb36b6c2d8a921712b5d56af7e2e6bab53e87801880d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
